### PR TITLE
Add speakers information document

### PR DESCRIPTION
**Pull request by dlsniper**
This should be sent as a link to our speakers after it's validated.

image

### CODE REVIEW

**Comment by alosdev** [comment]
how we can test the site?

**Comment by dlsniper** [comment]
Unfortunately I don't know. I've did this as the Code of Conduct so, unless we magically link from somewhere that I couldn't find, the page shouldn't be visible without a link (which was the intended idea from @stefanhoth)

**Comment by stefanhoth** [comment]
:x: Please wait on merging this

**Comment by alosdev** [comment]
ok found it
http://0.0.0.0:4000/speakers-information/

**Comment by dlsniper** [comment]
Ah, you meant the link itself, not how to do the local dev setup :)

**Comment by stefanhoth** [comment]
I renamed the link to be /speakers-faq and added a bunch of more details:
- layout
- question groups
- new header image
- a few more answers

See screenshot in the description.

Sorry to jump in like this @dlsniper I just wanted to get this done in a readable format quickly.

**Comment by dlsniper** [comment]
Sure, no worries. Merge it when you think it's ready and I'll prepare the e-mail to send to our speakers :)

**Comment by stefanhoth** [comment]
@alosdev be the judge on that.

**Pull request merged**
